config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new, :create]

  resources :designs

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]

  get 'search_articles', to: 'articles#search'
  get 'development', to: 'developments#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, use: :slugged
	belongs_to :user
	has_many :article_categories
	has_many :categories, through: :article_categories
	validates :title,  presence: true, length: { minimum: 10}
	validates :excerpt,  presence: true, length: { minimum: 5, maximum: 30}
	validates :description, presence: true, length: { minimum: 10}
	validates :user_id, presence: true

	def article_title
   		 return "#{title} #{description}".strip if (title || description)
    "No Articles"
  	end
  	
  	def self.search(search)
  		if search
  			where(["title LIKE ?", "%#{search}%"])
  			where(["description LIKE ?", "%#{search}%"])
  		else
  			all
  		end
  	end
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
	belongs_to :article
	belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :article_categories
	has_many :article, through: :article_categories
	validates :name, presence: true,  length: {minimum: 5, maximum: 15}
	validates_uniqueness_of :name
end

app/models/design.rb
class Design <  ActiveRecord::Base
extend FriendlyId
friendly_id :name, use: :slugged
belongs_to :users
validates :name, :design_description, presence: true
	

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/user.rb
class User <  ActiveRecord::Base
has_many :articles, dependent: :destroy
has_many :designs, dependent: :destroy
before_save { self.email = email.downcase }

validates :username, presence: true,
			uniqueness: { case_sensitive: false},
			length: {minimum: 3, maximum: 15} 
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true,
				uniqueness: { case_sensitive: false},
				length: { maximum: 150},
				format: { with: VALID_EMAIL_REGEX }
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user 
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

	def logged_in?
		!!current_user
	end

	def require_user
		if !logged_in?
		flash[:danger] = "You must be logged in to perform that action"
		redirect_to root_path
		end	
	end

	def not_found
		flash[:alert] = "Page not found"
  		render 'error_pages/_404'
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_id, only: [:edit, :update, :show]
	before_action :require_user, except: [:index, :show]
	before_action :require_same_user, only: [:edit, :update]
	before_action :article_users, only: [:index, :show]
	def index
	  	@articles = Article.search(params[:search])
	end

	def new
		@article = Article.new
	end

	def edit
	end 

	def create
	@article = Article.new(article_params)	
	@article.user = current_user
		if @article.save
		 		flash[:success] = "Article Created successfully"
		 		redirect_to article_path(@article)
		 	else
		 		render 'new'
		 	end
	end

	def update
			if @article.update(article_params)
			flash[:success] = "Article was successfully updated"
			redirect_to article_path(@article)
			else
				render 'edit'
			end
	end

	def show
	end

	def destroy
	end


	private 
	def set_id
		@article = Article.friendly.find(params[:id])
	end

	def require_same_user
		if current_user != @article.user 
			flash[:danger] = "You cannot delete/edit this article article"
			redirect_to root_path
		end
	end

	def article_params
		params.require(:article).permit(:title, :description, :excerpt, category_ids: [])
	end

	def article_users
	  	@user = User.all
	end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index 
		@categories = Category.all
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			flash[:success] = "Category Created Successfully"
			redirect_to categories_path
		else
			render 'new'
		end
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])
		if @category.update(category_params)
			flash[:success] = "Name Successfully updated"
			redirect_to category_path(@category)
		else
			render 'edit'
		end
	end

	def show
		@category = Category.find(params[:id])
		@category_articles = @category.article
	end
	# private methods
	private 
	def category_params
		params.require(:category).permit(:name)
	end
end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
before_action :set_id, only: [:edit, :update, :show]
	def index
		@designs = Design.all
	end

	def new
		if logged_in?
			@design = Design.new
		else
			flash[:danger] = "umm... You must be logged in to do this"
			redirect_to login_path
		end
	end

	def create
		@design = Design.new(design_params)
		if @design.save
	 		flash[:success] = "Design Created Successfully"
	 		redirect_to design_path(@design)
	 	else
	 		render 'new'
	 	end
	end

	def show
		
	end

	def update
		if @design.update(design_params)
			flash[:success] = "Design Updated awesomely!"
			redirect_to design_path(@design)
			else
				render 'edit'
			end
	end

	private
	def set_id
		@design = Design.friendly.find(params[:id])
	end
	def design_params
		params.require(:design).permit(:name, :design_description, :url, :id)
	end

end

app/controllers/developments_controller.rb
class DevelopmentsController < ApplicationController
	def index
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end

	def about
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have succesfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "Something went wrong with your login informations"
      render 'new'
    end
  end
    
  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_userid, only: [:update, :edit, :show]
	before_action :require_same_user, only:[:edit, :update, :destroy]
	before_action :require_admin, only:[:destroy]



	def index
		@users = User.all
	end

	def new
		not_found
		# @user = User.new
	end

	def create
		not_found
		# @user = User.new(user_params)
		# 	if @user.save
		# 		session[:user_id] = @user.id 
		# 		flash[:success] = "New User Created"
		# 		redirect_to user_path(@user)
		# 	else
		# 		render 'new'
		# 	end
	end

	def edit

	end

	def update 
		if @user.update(user_params)
			flash[:success] = "User data successfully updated"
			redirect_to user_path(@user)
		else
			redirect_to 'edit'
		end
	end 

	def show
	end 

	def destroy
		@user.destroy
		flash[:danger] = "User and Associated Article(s) destroyed successfully"
		redirect_to users_path
	end

	private
	def user_params
		params.require(:user).permit(:username, :password, :email)
	end

	def require_same_user
		if current_user != @user
			flash[:danger] = "you can only edit your own account"
		redirect_to root_path
		end
	end
	
	def set_userid
		@user = User.find(params[:id])
	end

	def require_admin
		if logged_in? && !current_user.admin?
			flash[:danger] = "Only Admin is supposed to do that "
		redirect_to root_path
		end
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title(page_title)
		content_for(:title) { page_title }
	end

	def active_class(link_path)
 		current_page?(link_path) ? "active" : ""
	end
end

app/views/articles/_articles.html.erb
<% obj.each do |article| %>
<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
		<div class="well well-lg">
			<div class="article-title">
			<%= link_to article.title, article_path(article) %>
			</div>
			<div class="article-body">
				<%= truncate(article.description, length: 50) %>
				<div class="meta">
					<small>Created By: <%= article.user.username if article.user%>, <%= time_ago_in_words(article.created_at)  %> ago, Last Updated: <%= time_ago_in_words(article.updated_at)  %> ago </small>
				</div>
			</div>
			<% if article.categories.any? %>
				<p>Categories: <%= render article.categories %> </p>
			<% end %>
			<% if logged_in? && (current_user == article.user)  %>
				<div class="article-actions">
					<%= link_to "Edit this Article", edit_article_path(article),  class: "btn btn-primary btn-xs" %>
					<%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete the article?"},  class: "btn btn-danger btn-xs" %> 
				</div>
			<% end %>
		</div>		
	</div>		
</div>
<% end %>

app/views/articles/_forms.html.erb
<%= form_for @article do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<%= f.label :excerpt %>
	<%= f.text_area :excerpt %>
	<%= f.label :description %>
	<%= f.text_area :description %>
	<%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb|  %>
		<% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
	<% end %>
	<%= f.submit "Create Article" %>
<% end %>

app/views/articles/edit.html.erb
<%= render 'forms' %>

app/views/articles/index.html.erb
<%= title "Blog Posts" %>
<div class="row article-section">
	<div class="large-12 columns">
      <div class="row collapse">
        <div class="small-10 columns">
        <%= form_tag(articles_path, :method => "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search Posts" %>
        </div>
        <div class="small-2 columns">
          <%= button_tag(type: :submit, class: "button alert radius postfix") do %>
        <i class="fi-magnifying-glass"></i>
        </div>
        <% end %>
		<% end %>
      </div>
    </div>
  </div>
<div class="large-12 columns">
	<% if @articles.present? %>
	<% else %>
		<h5>Nothing Found. <%=link_to "Go Back", articles_path %></h5>
	<% end %>	
</div>	
<div class= "large-12 columns">


	<% @articles.each do |article| %>
		<h2 class="article-title">
		<%= link_to article.title, article_path(article) %>
		</h2>
		<p><%= article.description %></p>
		<p><%= article.excerpt %></p>
		<p>Author <%= article.user.username %></p>
		<p class="time">Created At <%= article.created_at.strftime("%b %e, %l:%M %p") %>, Last updated on <%= article.updated_at.strftime("%b %e, %l:%M %p") %></p>
	<% end %>
</div>

app/views/articles/new.html.erb
<%= render 'forms' %>

app/views/articles/show.html.erb
	<%= @article.title %>
	<%= @article.description %>
	<%= @article.excerpt %>
	<% if @article.categories.any? %>
	<p>Categories: <%= render @article.categories %> </p>
	<p>Created By <%= @article.user.username %></p>
	<p class="time">Created At <%= @article.created_at.strftime("%b %e, %l:%M %p") %> ago, Updated At <%= @article.updated_at.strftime("%b %e, %l:%M %p") %> ago</p>
	<% end %>

app/views/categories/_category.html.erb
<div class="label round radius">
	<%= link_to category.name , category_path(category) %>
</div>

app/views/categories/_form.html.erb
<%= form_for(@category, :html => {role: "form"}) do |f| %>
	<div class="form-group">
			<%= f.label :name %> 
		</div>
		<div class="col-xs-8">
			<%= f.text_field :name, placeholder: "Enter Category Name", autofocus: true %>
		</div>
	</div>
	<div class="form-group text-center ">
		<div class="col-xs-12">
			<%= f.submit "Create Category", class: "button primary small" %>
		</div>
	</div>
<% end %>
	<div class="col-xs-12">
		<%= link_to "Back to Articles", articles_path %>
	</div>

app/views/categories/edit.html.erb
<%= render 'form' %>

app/views/categories/index.html.erb
<h1>
	Listing All Categories
</h1>
<div class="text-center">

	<% @categories.each do |category| %>
						<%= link_to "#{category.name}", category_path(category) %>
					<li><small><%= pluralize(category.article.count, "article") %></small></li>
				
	<% end %>
</div>

app/views/categories/new.html.erb
<%= render 'form' %>

app/views/categories/show.html.erb
<h1><%= "Category:" + @category.name %></h1>
<%= render 'articles/articles', obj: @category_articles %>
<div class="text-center">
<% if logged_in? %>
	<%= link_to "Edit Category Name" , edit_category_path(@category) %>
	</div>
	<% end %>
</div>

app/views/designs/_forms.html.erb
<%= form_for @design do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :design_description %>
	<%= f.text_area :design_description %>
	<%= f.label :url %>
	<%= f.text_field :url %>
	<%= f.submit "Add Design" %>
<% end %>

app/views/designs/edit.html.erb
<%= render 'forms' %>

app/views/designs/index.html.erb
<% @designs.each do |design| %>
	<%= link_to design.name, design_path(design) %>
	<%= link_to design.url %>
	<%= design.design_description %>
<% end %>

app/views/designs/new.html.erb
<%= render 'forms' %>

app/views/designs/show.html.erb
<%= @design.name %>
<%= link_to @design.url %>
<%= @design.design_description %>

app/views/developments/index.html.erb
<h1>This works?</h1>

app/views/error_pages/_404.html.erb
<h1 text-center>Page Not Found</h1>
<p>return to <%= link_to "Home", root_path %></p>

app/views/layouts/_footer.html.erb
<footer class="hp-footer">
	<div class="wrapper">
		<div class="row footer-content" align="center">
			<div class="ck-col-twelve">
				Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem inventore, nemo ipsa natus sapiente eos odit enim totam fugit aspernatur architecto culpa modi ipsam deserunt, beatae dolorem libero sed, iste!
			</div>
			<div class="ck-col-twelve">
				Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempore reiciendis fugiat illum cumque error vitae molestias accusantium expedita, asperiores. Tempora labore culpa minima, maiores consectetur deleniti suscipit cupiditate asperiores impedit?
			</div>
		</div>
	</div>
	<hr class="med-hr" align="center">
	<div class="wrapper">
		<div class="row">
			<div class="ck-col-twelve" align="center">
				<p class="copyright">All Rights Reserved &copy; <%= Time.now.year %>, <%= link_to "Himanshu Patel", root_path %> </p>
				<hr class="small-hr">
				<p class="impressum">Built with&nbsp;&nbsp; <i class="fa fa-coffee"></i>&nbsp;&nbsp;&amp; a lot of&nbsp;&nbsp;<i class="fa fa-heart"></i> </p>
			</div>
		</div>
	</div>
</footer>

app/views/layouts/_messages.html.erb
 <div class="row messages">
 	 <% flash.each do |name, e|  %>
 	 <div data-alert class="alert-box <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, e %>
      <a href="#" class="close">&times;</a>
	</div>
	 <% end %>
 </div>

app/views/layouts/_nav.html.erb
<header>
     
<div class="wrapper">
   <%= link_to "Himanshu Patel", root_path, id: "brand" %>
   <a href="#" class="burger-nav fa fa-1x fa-bars">Menu</a>
  <nav class="nav-main">
    
         <ul>
              <li class= "<%= active_class(root_path) %>"><%= link_to "Home", root_path %></li>
              <li class= "<%= active_class(about_path) %>"><%= link_to "About", about_path %></li>
              <li class= "<%= active_class(articles_path) %>"><%= link_to "Blog", articles_path %></li>
              <li class= "<%= active_class(designs_path) %>"><%= link_to "Designs", designs_path %></li>
              <li class= "<%= active_class(development_path) %>"><%= link_to "Development", development_path %></li>
              <li class= "<%= active_class(root_path) %>"><%= link_to "Achievements", root_path %></li>
            </ul>
  </nav>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title> Himanshu Patel - <%= yield :title %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= stylesheet_link_tag    "https://fonts.googleapis.com/css?family=Dancing+Script:400,700" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "https://use.fontawesome.com/0e96f0f28a.js" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <%= render 'layouts/messages' %>
  <%= render 'layouts/nav' %>
  <div class="wrapper">
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="content-wrapper">
	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga consequuntur tenetur veritatis aperiam, facere qui nisi, error, tempora aut exercitationem blanditiis at earum fugit asperiores, quis placeat odit impedit eveniet.
	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga consequuntur tenetur veritatis aperiam, facere qui nisi, error, tempora aut exercitationem blanditiis at earum fugit asperiores, quis placeat odit impedit eveniet.
	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga consequuntur tenetur veritatis aperiam, facere qui nisi, error, tempora aut exercitationem blanditiis at earum fugit asperiores, quis placeat odit impedit eveniet.
	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga consequuntur tenetur veritatis aperiam, facere qui nisi, error, tempora aut exercitationem blanditiis at earum fugit asperiores, quis placeat odit impedit eveniet.
</div>

app/views/pages/home.html.erb
<%= title "Home" %>
<div class="top-reset">
	<div class="wrapper">
		<div class="hero-unit slideExpandUp">
				<span class="hero-text"><h1>I am a hero text!</h1></span>
		</div>
	</div>
</div>
<section>
	<div class="wrapper">
		<row class="ck-col-twelve centered-text">
			<h3>here goes all data</h3>
		</row>
	</div>

	<h3>Blog Posts Goes Here</h3>
	<div class="wrapper">
			<div class="row">
				<div class="ck-col-four">
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, repudiandae, porro eius aut aspernatur delectus fuga. Recusandae, omnis? Alias veniam laboriosam tempora architecto voluptates, nesciunt pariatur perferendis, saepe deleniti impedit? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi a aspernatur, labore iure atque, at asperiores, eaque necessitatibus deleniti omnis tempore est explicabo nostrum minima harum animi amet expedita aliquam! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis eveniet dicta, ullam, id voluptate quam quae harum, molestiae veniam laboriosam ad enim alias. Quos corporis sunt sequi ea minima, tempora!  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum cumque consectetur voluptatem ut unde voluptas cupiditate, fugit commodi esse accusamus sint culpa natus libero, ipsum rerum atque distinctio ab? Dolorum?</p>
				</div>
				<div class="ck-col-four">
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, repudiandae, porro eius aut aspernatur delectus fuga. Recusandae, omnis? Alias veniam laboriosam tempora architecto voluptates, nesciunt pariatur perferendis, saepe deleniti impedit? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi a aspernatur, labore iure atque, at asperiores, eaque necessitatibus deleniti omnis tempore est explicabo nostrum minima harum animi amet expedita aliquam! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis eveniet dicta, ullam, id voluptate quam quae harum, molestiae veniam laboriosam ad enim alias. Quos corporis sunt sequi ea minima, tempora!  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum cumque consectetur voluptatem ut unde voluptas cupiditate, fugit commodi esse accusamus sint culpa natus libero, ipsum rerum atque distinctio ab? Dolorum?</p>
				</div>
				<div class="ck-col-four">
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, repudiandae, porro eius aut aspernatur delectus fuga. Recusandae, omnis? Alias veniam laboriosam tempora architecto voluptates, nesciunt pariatur perferendis, saepe deleniti impedit? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi a aspernatur, labore iure atque, at asperiores, eaque necessitatibus deleniti omnis tempore est explicabo nostrum minima harum animi amet expedita aliquam! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis eveniet dicta, ullam, id voluptate quam quae harum, molestiae veniam laboriosam ad enim alias. Quos corporis sunt sequi ea minima, tempora!  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum cumque consectetur voluptatem ut unde voluptas cupiditate, fugit commodi esse accusamus sint culpa natus libero, ipsum rerum atque distinctio ab? Dolorum?</p>
				</div>
			</div>
	</div>
	<hr class="med-hr" align="center">
	<div class="wrapper ">
		<div class="row">
			<div class="ck-col-twelve">
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, repudiandae, porro eius aut aspernatur delectus fuga. Recusandae, omnis? Alias veniam laboriosam tempora architecto voluptates, nesciunt pariatur perferendis, saepe deleniti impedit? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi a aspernatur, labore iure atque, at asperiores, eaque necessitatibus deleniti omnis tempore est explicabo nostrum minima harum animi amet expedita aliquam! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis eveniet dicta, ullam, id voluptate quam quae harum, molestiae veniam laboriosam ad enim alias. Quos corporis sunt sequi ea minima, tempora!  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum cumque consectetur voluptatem ut unde voluptas cupiditate, fugit commodi esse accusamus sint culpa natus libero, ipsum rerum atque distinctio ab? Dolorum?</p>
			</div>
			<div class="ck-col-twelve">
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, repudiandae, porro eius aut aspernatur delectus fuga. Recusandae, omnis? Alias veniam laboriosam tempora architecto voluptates, nesciunt pariatur perferendis, saepe deleniti impedit? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi a aspernatur, labore iure atque, at asperiores, eaque necessitatibus deleniti omnis tempore est explicabo nostrum minima harum animi amet expedita aliquam! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis eveniet dicta, ullam, id voluptate quam quae harum, molestiae veniam laboriosam ad enim alias. Quos corporis sunt sequi ea minima, tempora!  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum cumque consectetur voluptatem ut unde voluptas cupiditate, fugit commodi esse accusamus sint culpa natus libero, ipsum rerum atque distinctio ab? Dolorum?</p>
			</div>
			<div class="ck-col-twelve">
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, repudiandae, porro eius aut aspernatur delectus fuga. Recusandae, omnis? Alias veniam laboriosam tempora architecto voluptates, nesciunt pariatur perferendis, saepe deleniti impedit? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi a aspernatur, labore iure atque, at asperiores, eaque necessitatibus deleniti omnis tempore est explicabo nostrum minima harum animi amet expedita aliquam! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis eveniet dicta, ullam, id voluptate quam quae harum, molestiae veniam laboriosam ad enim alias. Quos corporis sunt sequi ea minima, tempora!  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum cumque consectetur voluptatem ut unde voluptas cupiditate, fugit commodi esse accusamus sint culpa natus libero, ipsum rerum atque distinctio ab? Dolorum?</p>
			</div>
		</div>
	</div>

</section>

app/views/users/_forms.html.erb
	<%= form_for @user do |f| %>
		<%= f.label :username %>
		<%= f.text_field :username %>
		<%= f.label :email %>
		<%= f.text_field :email %>
		<%= f.label :password %>
		<%= f.password_field :password %>
		<%= f.submit "Create User" %>
	<% end %>

app/views/users/edit.html.erb
<%= render 'forms' %>

app/views/users/index.html.erb
<%= title "Blog Users" %>
<% @users.each do |user| %>
	<%= user.username %>
	<%= user.email %>
	<li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
<% end %>

app/views/users/new.html.erb
<%= render 'forms' %>

app/views/users/show.html.erb
<%= @user.username %>
<%= @user.email %>